# Hospital Chat System Configuration

# Google Cloud Project Settings
gcp:
  project_id: "your-project-id"
  location: "us-central1"
  
# GCS Bucket Configuration
# Map your existing buckets to domains
buckets:
  nursing: "nursing"
  pharmacy: "pharmacy"
  po: "po"  # Purchase Orders / Procurement

# Vertex AI Search Configuration
# Datastores need to be created to enable AI search over your bucket contents
vertex_search:
  nursing:
    datastore_id: "nursing-datastore-v5"
    serving_config_id: "default_config"
  pharmacy:
    datastore_id: "pharmacy-datastore-v5"
    serving_config_id: "default_config"
  po:
    bucket: "po"  # HR bucket
    datastore_id: "po-datastore-v5"

# LLM Configuration
llm:
  model: "gemini-1.5-pro"
  temperature: 0.2
  max_output_tokens: 2048
  top_k: 40
  top_p: 0.95

# Document Processing
chunking:
  chunk_size: 800
  chunk_overlap: 200
  min_chunk_size: 100

# Retrieval Settings
retrieval:
  top_k: 5
  similarity_threshold: 0.7

# Web API Settings
api:
  host: "0.0.0.0"
  port: 8080
  max_conversation_history: 10
